backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: CMS - Create {{collection}} "{{slug}}"
    update: CMS - Update {{collection}} "{{slug}}"
    delete: CMS - Delete {{collection}} "{{slug}}"
    uploadMedia: CMS - Upload "{{path}}"
    deleteMedia: CMS - Delete "{{path}}"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "general"
    label: "General"
    files:
      - file: "src/general/data.json"
        label: "Navbar, Footer & Socials"
        name: "data"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar-element"}
          - {label: Logo, name: logo, widget: image}
          - {label: Logo Horizontal, name: logoHorizontal, widget: image}
          - {label: "Log in link", name: logInLink, widget: "string"}
          - {label: "Sign up link", name: signUpLink, widget: "string"}
          - label: Footer
            name: footer
            widget: object
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "text"}
              - label: Sign In Button
                name: signInButton
                widget: object
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Link, name: link, widget: string}
              - label: Sign Up Button
                name: signUpButton
                widget: object
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Link, name: link, widget: string}
              - {label: Footer Logo, name: logoFooter, widget: image}
              - {label: "Social Media Title", name: "socialMediaTitle", widget: "string"}
              - label: "Social Media"
                name: socialMedia
                widget: list
                fields:
                  - {label: Icon, name: icon, widget: image}
                  - {label: Link, name: link, widget: string}
              - {label: "Contact Title", name: "contactTitle", widget: "string"}
              - {label: Contact Icon, name: contactIcon, widget: image}
              - label: "Contacts"
                name: contacts
                widget: list
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Contact, name: contact, widget: string}
                  - label: Type
                    name: type
                    widget: select
                    required: false
                    default: null
                    options:
                      - {label: E-mail, value: "mailto:"}
                      - {label: Telephone, value: "tel:"}
      - file: "src/general/metaData.json"
        label: "Meta data"
        name: "metaData"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "meta-data"}
          - {label: Page Title, name: pageTitle, widget: string}