backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: CMS - Create {{collection}} "{{slug}}"
    update: CMS - Update {{collection}} "{{slug}}"
    delete: CMS - Delete {{collection}} "{{slug}}"
    uploadMedia: CMS - Upload "{{path}}"
    deleteMedia: CMS - Delete "{{path}}"

media_folder: static/img
public_folder: /img

collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    filter:
      field: language
      value: en
    fields:
      - {label: "Language", name: "language"}